##########################################################################################
# +------------------------------------------------------------------------------------+ #
# |                                                                                    | #
# |                           A complete plugin for hubs                               | #
# |                                                                                    | #
# |                      © 2024 - Developed by retiredbydavid                          | #
# |                                                                                    | #
# |                                                                                    | #
# |                                                                                    | #
# |                       Configure the plugin to your liking.                         | #
# +------------------------------------------------------------------------------------+ #
##########################################################################################

plugin-version: 1
#      _       _          ____             __ _
#     | | ___ (_)_ __    / ___|___  _ __  / _(_) __ _
#  _  | |/ _ \| | '_ \  | |   / _ \| '_ \| |_| |/ _` |
# | |_| | (_) | | | | | | |__| (_) | | | |  _| | (_| |
# \___/ \___/|_|_| |_|  \____\___/|_| |_|_| |_|\__, |
#                                              |___/

join:
  # Sound to play when a player joins
  # Use Bukkit Sound enum values
  sound: "ENTITY_CAT_AMBIENT"
  # Volume of the sound (0.0 to 1.0)
  volume: 1.0
  # Pitch of the sound (0.0 to 2.0)
  pitch: 1.0

join-message:
  enabled: true # Enable or disable
  lines:
    - "&7+-----------------------------------"
    - "&r"
    - "&r  &7Welcome, &b&n%player%&r &7to the server"
    - "&r"
    - "&r  &2&lWEBSITE &fwww.examplemc.net"
    - "&r  &3&lSTORE &fstore.examplemc.net"
    - "&r  &9&lDISCORD &fdiscord.examplemc.net"
    - "&r"
    - "&7------------------------------------"
effects:
  enabled: true
  list:
    - "SPEED 1"
    - "JUMP 2"
    # Example format: "EFFECT_NAME LEVEL"
    # Valid effects: SPEED, JUMP, STRENGTH, REGENERATION, etc.

message-custom:
  # No replace %$
  custom-join-message: "&8[&a+&8] &7%s"
  custom-quit-message: "&8[&c-&8] &7%s"
